DoAnCuoiKy/Source/WebsiteBanHang/WebsiteBanHang/Controllers/GuiTarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanHang.Models;
namespace WebsiteBanHang.Controllers
{
    public class GuiTarController : BaseController
    {
        WebSiteGuitarEntities db = new WebSiteGuitarEntities();

        #region[INDEX]
        public ActionResult Index()
        {

            IndextProduct ip = new IndextProduct();
            var productNew = (from p in db.SanPham orderby p.sp_Id descending select p).Take(8).ToList();
            for (int i = 0; i < productNew.Count; i++)
            {
                ip.New.Add(productNew[i]);
               
            }
           
            var productFeature = (from p in db.SanPham select p).ToList();
            for (int i = 0; i < productFeature.Count; i++)
            {
                ip.Fav.Add(productFeature[i]);
               
            }
            ViewBag.Name = BienToanCuc.Bien;
            return View(ip);
        }
        #endregion

        #region[CREATE]
        public ActionResult Create()
        {

            ViewBag.Name = BienToanCuc.Bien;
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection,SanPham sanpham)
        {
            string Ten = collection["txtTen"];
            int Gia = int.Parse(collection["txtGia"]);
            int SoLuong = int.Parse(collection["txtSoLuong"]);
            string Loai = collection["txtLoai"];
            string MauSac = (collection["txtMauSac"]);
            string HA = collection["txtHA"];
           
            sanpham.sp_TenSanPham = Ten;
            sanpham.sp_GiaTien = Gia;
            sanpham.sp_Loai = Loai;
            sanpham.sp_HinhAnh = HA;
            sanpham.sp_MauSac = MauSac;
            sanpham.sp_SoLuong = SoLuong;
            db.SanPham.Add(sanpham);

            db.SaveChanges();
            return RedirectToAction("Update");
        }


        #endregion
        public ActionResult DeleteAll()
        {
            for (int i = 0; i < db.ChiTietGioHang.ToList().Count(); i++)
            {
                db.ChiTietGioHang.Remove(db.ChiTietGioHang.ToList()[i]);

            }
            db.SaveChanges();
            return RedirectToAction("Cart");
        }

        #region[Update]
        public ActionResult Update()
        {
            String chuoi="";
            List<SanPham> list = new List<SanPham>();
             var Listsp = (from p in db.SanPham select p).ToList();
             for (int i = 0; i < Listsp.Count; i++)
             {
                 list.Add(Listsp[i]);
                 //chuoi += "<tr>";
                 //chuoi += "<td class=\"image\"><a href=\"#\"><img title=\"product\" alt=\"product\" src=\"" + Listsp [i].sp_HinhAnh+ "\" height=\"50\" width=\"50\"></a></td>";
                 //chuoi += "<td class=\"name\"><a href=\"#\">"+Listsp[i].sp_TenSanPham+"</a></td>";
                 //chuoi += "<td class=\"model\">"+Listsp[i].sp_Loai+"</td>";
                 //chuoi += "<td class=\"quantity\"><input type=\"text\" size=\"1\" value=\""+Listsp[i].sp_SoLuong+"\" name=\"quantity[40]\" class=\"span1\"></td>";
                 //chuoi += "<td class=\"price\">"+Listsp[i].sp_GiaTien+"</td>";
                 //chuoi += "<td class=\"total\">"+Listsp[i].sp_MauSac+"</td>";
                 //chuoi += "<td class=\"remove-update\">";
                 //chuoi += "<a href=\"#\" class=\"tip remove\" title=\"Remove\"><img src=\"images/remove.png\" alt=\"\"></a>";
                 //chuoi += " <a href=\"#\" class=\"tip update\" title=\"Update\"><img src=\"images/update.png\" alt=\"\"></a>";
                 //chuoi += "</td>";
                 //chuoi += "</tr>";
             }
            ViewBag.ListSanPham = chuoi;

            ViewBag.Name = BienToanCuc.Bien;
            return View(list);

        }
         #endregion

        #region[Edit]
        public ActionResult Edit(int id)
        {

            ViewBag.Name = BienToanCuc.Bien;
            var sp = db.SanPham.First(m => m.sp_Id == id);
            return View(sp);

        }
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            SanPham sp = db.SanPham.First(m =>m.sp_Id == id);
            sp.sp_TenSanPham = collection["sp_TenSanPham"];
            sp.sp_GiaTien = int.Parse(collection["sp_GiaTien"]);
            sp.sp_Loai = collection["sp_Loai"];
            sp.sp_SoLuong = int.Parse(collection["sp_SoLuong"]);
            sp.sp_MauSac = collection["sp_MauSac"];
            sp.sp_HinhAnh = collection["sp_HinhAnh"];
            UpdateModel(sp);
            db.SaveChanges();
            return RedirectToAction("Update");
        }
        #endregion

        #region[Delete]
       
        public ActionResult Delete(int id)
        {
            SanPham sp = db.SanPham.First(m => m.sp_Id == id);
            db.SanPham.Remove(sp);
            UpdateModel(sp);
            db.SaveChanges();
            return RedirectToAction("Update");
        }
        #endregion

        #region[List]

        public ActionResult List()
        {

            List<SanPham> List = new List<SanPham>();
            var ListSanPham = db.SanPham.ToList();
            List<SanPham> TempList = new List<SanPham>();
            TempList = (List<SanPham>)TempData["List"];
            String ThongBao=(String)TempData["TrangThai"];
            if (ThongBao !=  "Khong Thay")
            {
                if (TempList != null)
                {


                    for (int i = 0; i < TempList.Count(); i++)
                    {
                        List.Add(TempList[i]);
                    }
                }
                else
                {
                    for (int i = 0; i < ListSanPham.Count(); i++)
                    {
                        List.Add(ListSanPham[i]);
                    }
                }
            }
            else
            {
                ViewBag.ThongBao = TempData["TrangThai"];
            }
            ViewBag.Name = BienToanCuc.Bien;
            return View(List);
        }
        #endregion

        #region[Bass]

        public ActionResult Bass()
        {
            List<SanPham> List = new List<SanPham>();
            var ListSanPham = db.SanPham.ToList();
            for (int i = 0; i < ListSanPham.Count(); i++)
            {
                if (ListSanPham[i].sp_Loai == "Bass") 
                {
                    List.Add(ListSanPham[i]);
                }
            }

            ViewBag.Name = BienToanCuc.Bien;
            return View(List);

        }
        #endregion

        #region[Dien]

        public ActionResult Dien()
        {
            List<SanPham> List = new List<SanPham>();
            var ListSanPham = db.SanPham.ToList();
            for (int i = 0; i < ListSanPham.Count(); i++)
            {
                if (ListSanPham[i].sp_Loai == "Điện")
                {
                    List.Add(ListSanPham[i]);
                }
            }

            ViewBag.Name = BienToanCuc.Bien;
            return View(List);
        }
        #endregion

        #region[Classic]
        public ActionResult Classic()
        {
            List<SanPham> List = new List<SanPham>();
            var ListSanPham = db.SanPham.ToList();
            for (int i = 0; i < ListSanPham.Count(); i++)
            {
                if (ListSanPham[i].sp_Loai == "Classic")
                {
                    List.Add(ListSanPham[i]);
                }
            }

            ViewBag.Name = BienToanCuc.Bien;
            return View(List);
        }
        #endregion

        #region[Acaustic]
        public ActionResult Acaustic()
        {
            List<SanPham> List = new List<SanPham>();
            var ListSanPham = db.SanPham.ToList();
            for (int i = 0; i < ListSanPham.Count(); i++)
            {
                if (ListSanPham[i].sp_Loai == "Acaustic")
                {
                    List.Add(ListSanPham[i]);
                }
            }

            ViewBag.Name = BienToanCuc.Bien;
            return View(List);
        }
        #endregion
        
        #region[Login]
        public ActionResult Login(String username, String password)
        {
            var List = db.TaiKhoan.ToList();
            for (int i = 0; i < List.Count(); i++)
            {
                if ((List[i].tk_TenDangNhap == username) && (List[i].tk_MatKhau == password))
                {
                    BienToanCuc.tkdn=List[i];
                    if (List[i].tk_Loai == 0)
                    {
                        BienToanCuc.Bien = "admin";
                        return RedirectToAction("Index");

                    }
                    if (List[i].tk_Loai == 1)
                    {
                        BienToanCuc.Bien = "member";

                        return RedirectToAction("Index");
                    }

                }
            }
            return RedirectToAction("Index");
        }
        #endregion

        #region[SignUp]
        public ActionResult Success()
        {
            return View();
        }
        public ActionResult SignUp()
        {
            ViewBag.Name = BienToanCuc.Bien;
            return View();
        }
        [HttpPost]
        public ActionResult SignUp(FormCollection collection, TaiKhoan tk)
        {
            string Tendn = collection["tendangnhap"];
            string pass = collection["password"];
            string Ten = collection["tennguoidung"];
            string DiaChi = collection["diachi"];
            string sdt = (collection["sodienthoai"]);
            string mail = collection["email"];


            tk.tk_TenDangNhap = Tendn;
            tk.tk_MatKhau = pass;
            tk.tk_TenNguoiDung = Ten;
            tk.tk_DiaChi = DiaChi;
            tk.tk_SoDienThoai = sdt;
            tk.tk_Email = mail;
            tk.tk_Loai = 1;
            db.TaiKhoan.Add(tk);

DoAnCuoiKy/Source/WebsiteBanHang/WebsiteBanHang/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Guitar Shop - Responsive E-commerce Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @Styles.Render("~/Content/css")
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700|Arvo:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery_cur")
    <!--MENU-->
    <script type="text/javascript">
        $(document).ready(function ($) {
            $('#mega-menu-3').dcMegaMenu({
                rowItems: '2',
                speed: 'fast',
                effect: 'fade'
            });
        });
    </script>
</head>
<body>
    <div id="page_wrap">
        <header>
            <div id="top">
                <span style="font-size:15px">Hello @ViewData["manufacturers"] !!!</span>
                <div>
                    <p>
                        Language:
                        <label>
                            <select>
                                <option selected>English </option>
                                <option>German</option>
                                <option>Spanish</option>
                            </select>
                        </label>
                    </p>
                    <p>
                        Currency:
                        <label>
                            <select>
                                <option selected>US Dollar - USD </option>
                                <option>Euro - EUR</option>
                                <option>British Pound - GBP</option>
                            </select>
                        </label>
                    </p>
                </div>
            </div><!--end:top-->
            <div id="top2">
                <ul class="myaccountmenu">
                    <li>@Html.ActionLink("Tài Khoản","Account","Guitar")</li>
                 
                    <li>@Html.ActionLink("Đăng Xuất", "Logout", "Guitar")</li>
                   
                </ul>
                <div id="login-box" class="login-popup">
                    <a href="#" class="close"><img src="/Images/process-stop.png" class="btn_close" title="Close Window" alt="Close" /></a>
                    <form method="post" class="signin" action="/Guitar/Login">

                        <fieldset class="textbox">
                            <label class="username">
                                <span>Tên Đăng Nhập</span>
                                <input id="username" name="username" value="" type="text" autocomplete="on" placeholder="Username">
                            </label>
                            <label class="password">
                                <span>Mật Khẩu</span>
                                <input id="password" name="password" value="" type="password" placeholder="Password">
                            </label>
                            <button class="submit button" type="submit">Đồng ý</button>
                            <p>
                                <a class="forgot" href="#">Bạn quên mật khẩu?</a> / <a class="register" href="register.html">Tạo tài khoản</a>
                            </p>
                        </fieldset>

                       
                        </form>
</div>

            </div><!--end:top2-->
            <div id="top3">

                <h1 class="logo"><a href="#">Shopy Mart</a></h1>

                <form action="/Guitar/Search" method="post" class="search_bar">
                    <fieldset>
                        <input type="text" name="search" class="search" value="Enter a keywords..." onblur="if (this.value == ''){this.value = 'Enter a keywords...'; }" onfocus="if (this.value== 'Enter a keywords...') {this.value = ''; }" />
                        <input type="submit" name="submit" value="Search" class="submit" />
                    </fieldset>
                </form>
            </div><!--end:top3-->
        </header>
        <div id="container">
            <nav>
                <ul id="mega-menu-3" class="mega-menu">
                    <li class="first">  @Html.ActionLink("Home", "Index", "GuiTar")</li>
                    <li>
                        @Html.ActionLink("Guitar", "List", "GuiTar")
                        <ul>
                            <li> @Html.ActionLink("Bass", "Bass", "GuiTar")</li>
                            <li> @Html.ActionLink("Acaustic", "Acaustic", "GuiTar")</li>

                            <li> @Html.ActionLink("Classic", "Classic", "GuiTar")</li>
                            <li> @Html.ActionLink("Điện", "Dien", "GuiTar")</li>

                        </ul>
                    </li>
                    <li>
                        @Html.ActionLink("Sản Phẩm", "Update", "GuiTar")
                        <ul>
                            <li>
                                @Html.ActionLink("Udate", "Update", "GuiTar")
                            </li>

                            <li>
                                @Html.ActionLink("Create", "Create", "GuiTar")

                            </li>

                        </ul>
                    </li>
                    
                    <li>
                        @Html.ActionLink("Đơn Đặt Hàng", "ListPDH", "GuiTar")
                     
                    </li>
                    <li>
                        @Html.ActionLink("Thống Kê", "ThongKe", "GuiTar")

                    </li>
                    <li>
                        <a href="/Guitar/About">Giới Thiệu</a>

                    </li>
                    <li><a href="/Guitar/Contact">Liên Hệ</a></li>
                </ul>
            </nav><!--end:grey-->



            @RenderBody()


            <footer>
                <div class="content-wrap">
                    <div class="one-fourth first">
                        <h4>Thông tin</h4>
                        <ul>
                            <li><a href="http://html5awesome.com/themeforest/shopymart/about.html">Giới thiệu</a></li>
                            <li><a href="#">Thông tin giao hàng</a></li>
                            <li><a href="#">Chính sách bảo mật</a></li>
                            <li><a href="#">Terms &amp; Điều khoản sử dụng</a></li>
                        </ul>
                    </div>
                    <div class="one-fourth">
                        <h4>Dịch vụ khách hàng</h4>
                        <ul>
                            <li><a href="contact.html">Liên hệ</a></li>
                            <li><a href="#">Trả về vận chuyển</a></li>
                            <li><a href="#">An toàn hàng</a></li>
                        </ul>
                    </div>
                    <div class="one-fourth">
                        <h4>Tính năng bổ sung</h4>
                        <ul>
                            <li><a href="#">Thương hiệu</a></li>
                            <li><a href="#">Các chi nhánh</a></li>
                            <li><a href="#">Đặc biệt</a></li>
                        </ul>
                    </div>
                    <div class="one-fourth">
                        <h4>Tài khoản của tôi</h4>
                        <ul>
                            <li><a href="account.html">Tài khoản của tôi</a></li>
                            <li><a href="#">Lịch sử đặt hàng</a></li>
                            <li><a href="wishlist.html">Ưa thích</a></li>
                            <li><a href="#">Bản tin</a></li>
                        </ul>
                    </div>
                </div>
                <div class="content-wrap">
                    <div style="clear:both; display:block;" class="social-wrap"></div>
                    <ul class="social">
                        <li><a href="#" class="tip" title="Facebook"><img src="/Images/social-icon-facebook.png" alt="Facebook"></a></li>
                        <li><a href="#" class="tip" title="Dribbble"><img src="/Images/social-icon-dribbble.png" alt="Dribbble"></a></li>
                        <li><a href="#" class="tip" title="Flickr"><img src="/Images/social-icon-flickr.png" alt="Flickr"></a></li>
                        <li><a href="#" class="tip" title="Pinterest"><img src="/Images/social-icon-pinterest.png" alt="Pinterest"></a></li>
                        <li><a href="#" class="tip" title="Twitter"><img src="/Images/social-icon-twitter.png" alt="Twitter"></a></li>
                        <li><a href="#" class="tip" title="RSS"><img src="/Images/social-icon-rss.png" alt="RSS"></a></li>
                    </ul>
                    <ul class="payment">
                        <li><a href="#" class="tip" title="Paypal"><img src="/Images/payment-icon-paypal.png" alt="Paypal"></a></li>
                        <li><a href="#" class="tip" title="American Express"><img src="/Images/payment-icon-ae.png" alt="American Express"></a></li>
                        <li><a href="#" class="tip" title="Discover"><img src="/Images/payment-icon-discover.png" alt="Discover"></a></li>
                        <li><a href="#" class="tip" title="Master Card"><img src="/Images/payment-icon-mastercard.png" alt="Master Card"></a></li>
                        <li><a href="#" class="tip" title="Visa"><img src="/Images/payment-icon-visa.png" alt="Visa"></a></li>
                    </ul>
                    <p style="clear:both; display:block;">&copy; 2013 <a href="index-2.html">GuitarShop</a>, All Rights Reserved. Designed by: <a href="#">louiejiemahusay</a></p>
                </div>
            </footer>
        </div><!--end:container-->
    </div><!--end:page_wrap-->
    <script type="text/javascript">
        //------JCAROUSEL-------------
        function mycarousel_initCallback(carousel) {
            // Disable autoscrolling if the user clicks the prev or next button.
            carousel.buttonNext.bind('click', function () {
                carousel.startAuto(0);
            });
            carousel.buttonPrev.bind('click', function () {
                carousel.startAuto(0);
            });
            // Pause autoscrolling if the user moves with the cursor over the clip.
            carousel.clip.hover(function () {
                carousel.stopAuto();
            }, function () {
                carousel.startAuto();
            });
        };
        jQuery(document).ready(function () {
            jQuery('#mycarousel, #mycarouselnew').jcarousel({
                auto: 0,
                wrap: 'last',
                initCallback: mycarousel_initCallback
            });
        });
    </script>
    <script type="text/javascript">
        jQuery(function ($) {
            $(".tweet").tweet({
                join_text: "auto",
                username: "html5awesome",
                avatar_size: 48,
                count: 3,
                auto_join_text_default: " we said, ",
                auto_join_text_ed: " we ",
                auto_join_text_ing: " we were ",
                auto_join_text_reply: " we replied ",
                auto_join_text_url: " we were checking out ",
                loading_text: "loading tweets..."
            });
        });
    </script>
    <script type="text/javascript">
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "../../../connect.facebook.net/en_US/all.js#xfbml=1";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
</body>
</html>